SCENES:
- Beechwood_0_int    
- Benevolence_1_int
- house_double_floor_lower
- Ihlen_0_int
- Merom_1_int
- Pomaria_0_int
- restaurant_brunch
- Wainscott_1_int
- Beechwood_1_int
- Benevolence_2_int
- house_double_floor_upper
- Ihlen_1_int
- office_large
- Pomaria_1_int
- Rs_int
- Benevolence_0_int
- grocery_store_cafe
- house_single_floor
- Merom_0_int
- Pomaria_0_garden
- Pomaria_2_int
- Wainscott_0_int